### ISSUE TITLE
sigreturn on macOS 10.14 Beta on functions including (quit)

### ISSUE THREAD

**Issue by currymj** [Clozure/ccl#146] opened 2018-08-31 20:19 UTC
On a beta machine, if I try:

```
Michaels-MacBook-Pro-6% ccl64
Clozure Common Lisp Version 1.11.5  (DarwinX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (quit)
sigreturn returned
? for help
[5280] Clozure CL kernel debugger: b
current thread: tcr = 0x103010, native thread ID = 0x307, interrupts enabled


(#x0000000000647EE0) #x00003000006326A4 : #<Function %NANOSLEEP #x00003000006323AF> + 757
(#x0000000000647F68) #x000030000064BBBC : #<Function HOUSEKEEPING-LOOP #x000030000064B9DF> + 477
(#x0000000000647FB8) #x000030000064C274 : #<Function (:INTERNAL (TOPLEVEL-FUNCTION (LISP-DEVELOPMENT-SYSTEM T))) #x000030000064C16F> + 261
[5280] Clozure CL kernel debugger: 
```

I get a similar result trying to load quicklisp, although loading my own test file that just defines a simple function works fine.

**Comment by xrme** [comment] 2018-08-31 22:30
I think I have a simple fix for the 1.12 development branch.  If it seems stable there, I'll back-port it to 1.11.5 shortly.

**Comment by xrme** [comment] 2018-08-31 23:29
212c2544 seems to fix 1.12-dev.

I did some light testing on an old 10.6 system, and while it seems to work for the most part (i.e, it works to do `(rebuild-ccl :clean t)`), when I evaluate `(quit)`, I see errors like this:
```
Clozure Common Lisp Version 1.12-dev (v1.12-dev.3-18-g212c2544) DarwinX8664
? (quit)
> Error: Fault during read of memory address #x0
> While executing: 0, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
$ 
```
And for 32-bit:
```
Clozure Common Lisp Version 1.12-dev (v1.12-dev.3-18-g212c2544) DarwinX8664
? (quit)
> Error: Fault during read of memory address #x0
> While executing: 0, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

Frankly, I am not much inclined to worry about this, even if I port 212c2544 to 1.11.5.

**Comment by edoneel** [comment] 2018-09-01 10:04
Hi,  
  
Thanks!  It works perfectly.  
  
The comment in the change says 10.4 not 10.14.  Right now we all know what it means, but, it might be confusing at some point :-)  
  
cheers  
bruce

**Comment by xrme** [comment] 2018-10-31 01:54
It is beginning to look like it isn't safe to get rid of DarwinSigReturn on pre-Mojave systems.

Things seem to work most of the time, but there are definitely issues.

I'm going to quote some mail from openmcl-devel that shows some (fairly heavyweight) steps to reproduce:

> Clone the following into quicklisp/local-projects:
> 
>     https://gitlab.common-lisp.net/dcooper/zacl.git
>     https://github.com/gendl/aserve.git
>     https://gitlab.common-lisp.net/gendl/gendl.git
> 
> Then:
> 
>   (ql:quickload :gendl)
>   (gendl:start-gendl!)
> 
> That should print a banner and let you know which port the webserver is running on. 
> 
> Now go to the following URL in your browser:
>   
>    http://localhost:9000/tasty (or whatever the port is)
> 
> Accept the default robot:assembly.
> 
> Hover over the root node in the tree at upper-left and see the "Pencil" icon show up. Click the Pencil icon. 
> 
> This should result in the reported crash. 
> 
> The crash is happening some time during the call to the gdlAjax function, which is invoked through an Ajax call when clicking that "pencil" hover-over icon. The gdlAjax function is defined in the file gendl/gwl/ajax/source/ajax.lisp. 
> 

My reply:

> I think https://github.com/Clozure/ccl/commit/212c25448fb1743c3c51707e69a8b7a604e714a6 is not as problem-free as I originally thought it might be.
> 
> If I run a CCL IDE that includes that change on a High Sierra system (like the test ccl.pkg), then I see a crash.  But when I used a command-line lisp, I didn't see the crash, oddly enough.
> 
> If I take that change out (i.e., revert 212c2544), it works fine.
> 
> On the other hand, if I run the Lisp installed from the test ccl.pkg on a macOS Mojave system, your test case appears to work fine.
> 
> I wish I remembered why we needed the DarwinSigReturn workaround in the first place.  It looks like it is going to be necessary to detect at runtime whether we are on a pre-Mojave macOS, and leave the DarwinSigReturn thing in place if so.
>

**Comment by xrme** [comment] 2018-11-14 04:29
I'm also seeing crashes into the lisp kernel debugger when doing `make certify-books-short` from acl2-8.1 sources when running on Mojave.

**Comment by xrme** [comment] 2018-11-17 23:34
It seems that there's a third argument to the sigreturn system call on Mojave.  From the _sigtramp disassembly, we see:
```
    0x7fff77485b43 <+35>: movq   %rbx, %rdi
    0x7fff77485b46 <+38>: movl   $0x1e, %esi
    0x7fff77485b4b <+43>: movq   %r12, %rdx
    0x7fff77485b4e <+46>: callq  0x7fff77488594            ; symbol stub for: __sigreturn
```

The High Sierra sigtramp doesn't put anything in %rdx.

I have no idea what this extra argument is (and I don't see the Mojave sources on opensource.apple.com yet).

https://trac.clozure.com/ccl/changeset/11565 is a breadcrumb.  Other archaeology leads me to beleive that we're in this situation because (at one point at least) sigaltstack isn't (or wasn't) thread-local on Darwin.

**Comment by xrme** [comment] 2018-11-24 05:03
Another test case:

On macOS Mojave (earlier macOS versions work as expected):

1. build acl2-8.1
2. start acl2 and then evaluate
```
(thm (equal (append (append x y) x y x y x y x y)
           (append x y x y x y x y x y)))
```
3. hit C-c and observe that CCL enters the lisp kernel debugger
```
Unhandled exception 4 at 0x7fff77485b53, context->regs at #x70000b261590
? for help
[31147] Clozure CL kernel debugger:
```

**Comment by xrme** [comment] 2018-11-25 01:45
This exception (4 is SIGILL) is because the call to sigreturn in the sigtramp routine returned unexpectedly, and there's helpfully an illegal instruction there to catch that unexpected case.

**Comment by xrme** [comment] 2018-12-10 10:35
https://opensource.apple.com/release/macos-1014.html is now available (but they say "coming soon" for the sources for xnu-4903.201.2, which is probably what I really need to figure out what the third arg to sigreturn is.)

**Comment by rprimus** [comment] 2018-12-11 10:11
Tue Dec 11 10:11:28 GMT 2018

@xrme 

http://newosxbook.com/xxr/index.jl?q=sigreturn&ver=xnu-4903.221.2&case=false&def=false

**Comment by xrme** [comment] 2019-01-01 03:31
I ran a 1.11.5 binary under a Mojave debug kernel.  I got, as I feared I would, the following message:

```
process dx86cl64[405] sigreturn token mismatch: received 0x7ffeefbff120 expected 0xb993f3f80d520774
```

After this debug message is printed, the sigreturn system call returns with an error code.

The Mojave sources contain code to mitigate a class of attacks ("sigreturn oriented programming") described in, for example, https://dl.acm.org/citation.cfm?id=2650802.  It seems that this mitigation breaks a technique that CCL has been using.

**Comment by xrme** [comment] 2019-01-11 03:40
Thanks to some help from Apple DTS, I committed dd5622e9, and this really does seem to make CCL compatible with macOS Mojave.

**Comment by svspire** [comment] 2019-01-13 20:48
dd5622e9da69edc48dbf97c6caa6f3a7e16f932b Seems to still work fine on OSX 10.9.5 in terminal mode and as a GUI app.

**Comment by stoney** [comment] 2019-01-21 20:57
Are we going to see the Mac App Store version of Clozure CL updated soon? I'm waiting for that since my attempts to build it from this repos + comments haven't worked.

**Comment by xrme** [comment] 2019-01-27 01:01
I just submitted an updated Mac App Store version of Clozure CL.  It now has to get through app review.  This seems to take about a week.  It might take a little longer if the app review team identifies any issues that need to be corrected.

I'll post a note when it is approved (as I hope it will be).

**Closed** 2024-10-17 20:07 UTC
