### ISSUE TITLE
CCL 1.11.5 (WindowsX8664) does not exit cleanly from REPL

### ISSUE THREAD

**Issue by bcalco** [Clozure/ccl#183] opened 2019-01-09 20:39 UTC
The `(quit)` command ends the REPL but it does not let go - it just hangs. Reproducible via both git bash (MINGW64) and on DOS prompt on Windows 10. Have to go into Task Manager, find the process, and kill the uncivil way. This is a showstopping issue for me. Maybe there is a way to do it, as this is the first time I'm evaluating it, andI'm just missing something?

**Comment by xrme** [comment] 2019-01-10 03:06
duplicate of #24

**Closed by xrme** 2019-01-10 03:06 UTC
