### ISSUE TITLE
I cannot run CCL 1.12 on Windows 10 20H2

### ISSUE THREAD

**Issue by veer66** [Clozure/ccl#353] opened 2020-12-22 12:16 UTC
I got following error message.

```
> .\wx86cl64.exe -V
unexpected TLS index value: wanted 16, got 17
```

**Comment by phoe** [comment] 2020-12-22 12:17
Duplicate of https://github.com/Clozure/ccl/issues/311

**Closed by phoe** 2020-12-22 12:17 UTC
