### ISSUE TITLE
It won't work on Windows with TLS error

### ISSUE THREAD

**Issue by bigos** [Clozure/ccl#201] opened 2019-04-14 22:29 UTC
I have copied downloaded ccl to c:/ folder as there is not windows specific instructions
nothing seems to work

c:/ccl $ ./wx86cl64.exe -n
unexpected TLS index value: wanted 6, got 26
c:/ccl $ ./wx86cl.exe -V
unexpected TLS index value: wanted 7, got 27
c:/ccl $

**Comment by bigos** [comment] 2019-04-21 09:11
It seems to be environment related. This time it was run in a different folder and with the -n options I had some success.

> 
> PS C:\Users\Jacek\Downloads\ccl-1.11.5-windowsx86\ccl> .\wx86cl64.exe --help
> unexpected TLS index value: wanted 6, got 26
> PS C:\Users\Jacek\Downloads\ccl-1.11.5-windowsx86\ccl> .\wx86cl64.exe -n
> Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)
> 
> For more information about CCL, please see http://ccl.clozure.com.
> 
> CCL is free software.  It is distributed under the terms of the Apache
> Licence, Version 2.0.
> ? (+ 1 2 3)
> 6

**Comment by xrme** [comment] 2019-04-22 03:23
CCL tries to reserve some contiguous TLS slots at startup time. See `reserve_tls_slots()` (https://github.com/Clozure/ccl/blob/master/lisp-kernel/windows-calls.c#L1036). If it can't do this, it complains in the manner that you described.

I am not sure what causes TLS slots to get used up before CCL tries to reserve them.

CCL wants slots 30 through 63.  The code assumes that TLS slots are allocated in order, but maybe that's not true?  Maybe there's no need to give up if some slot under 30 is already reserved, as long as we can reserve slots 30 through 63?

**Comment by bigos** [comment] 2019-04-22 09:56
http://www.nynaeve.net/?p=190
the last paragraph mentions some possible magic happening behind the scenes.

**Comment by eugeneia** [comment] 2020-05-20 15:51
I happen to have a windows 10 box at hand and can reproduce this. Might try to formulate a fix over the weekend, however be warned that I don't know much about windows hacking.

@xrme can you explain to me what these TLS slots are used for, why CCL reserves them, why we want their IDs to be consecutive and in order (is this just an implementation detail or a hard requirement), and why CCL seems to work without reserving TLS slots / what limitations apply when we don't have them?

**Comment by xrme** [comment] 2020-05-20 15:59
This is a duplicate of #311 (wherein I suggest a fix).

**Closed by xrme** 2020-05-20 15:59 UTC
