### ISSUE TITLE
Cyrillic characters are shown incorrectly in the console

### ISSUE THREAD

**Issue by budden** [Clozure/ccl#104] opened 2018-01-15 10:54 UTC
chcp 65001, setting font to Lucida Console, -K utf-8, -K :utf-8 do not help. 
Using 64-bit CCL 11.1
Windows 10 64x Russian Edition

**Comment by vityok** [comment] 2018-01-17 15:29
Hi @budden , could you please be more specific? Do you mean that the terminal is able to display Cyrillic characters whereas CCL can't print them correctly?

**Comment by budden** [comment] 2018-01-17 19:49
Hi! Added info on OS into the bug title, and also recorded a demo video: https://youtu.be/Y11V4WTng0s
And PS, console is capable of displaying cyrillic:

```
c:\yar\sbcl\1.4.2-win>chcp 866
Текущая кодовая страница: 866

c:\yar\sbcl\1.4.2-win>echo Привет
Привет

c:\yar\sbcl\1.4.2-win>chcp 65001
Active code page: 65001

c:\yar\sbcl\1.4.2-win>echo Привет
Привет

c:\yar\sbcl\1.4.2-win>
```

**Comment by vityok** [comment] 2018-01-19 12:02
But why are you trying to specify UTF-8 instead of CP-866?

**Comment by budden** [comment] 2018-01-19 13:58
Does CCL support CP-866? That's not obvious from the docs. Or what you
do mean? I can reformulate my question: how can I see cyrillic
characters in the console in CCL and enter them in CCL, Windows 10.

2018-01-19 15:02 GMT+03:00, Victor <notifications@github.com>:

**Comment by vityok** [comment] 2018-01-22 12:08
Found the following in the release notes:

```
The -K or --terminal-encoding command-line argument can be used to
set the value of this variable (the argument is processed before the
standard streams are created.)  The string which is the value of
the -K/--terminal-encoding argument is uppercased and interned in
the KEYWORD package; if an encoding named by that keyword exists,
CCL:*TERMINAL-CHARACTER-ENCODING-NAME* is set to the name of that
encoding.
```

but it appears that at least the CCL that I've got doesn't recognize neither CP-866 nor CP866. And this seems to be the case for the rest, as supported character encodings can be discovered using the `list-character-encodings` function from `l1-unicode.lisp`:

```lisp
(ccl:list-character-encodings)
;; => (:GB2312 :UCS-2BE :UTF-32LE :ISO-8859-11 :ISO-8859-7 :CP936 :ISO-8859-15
;; :ISO-8859-13 :UTF-8 :WINDOWS-31J :ISO-8859-14 :US-ASCII :ISO-8859-6
;; :ISO-8859-4 :UTF-16 :UTF-32BE :ISO-8859-16 :ISO-8859-10 :ISO-8859-9
;; :UCS-2 :ISO-8859-5 :UTF-16LE :ISO-8859-2 :EUC-JP :ISO-8859-1 :ISO-8859-3
;; :ISO-8859-8 :UTF-32 :UCS-2LE :MACINTOSH :UTF-16BE)
```

and the CP-866 is not in the list.

But now you know where it can be added.

With best regards,

**Comment by budden** [comment] 2018-01-22 12:36
> but it appears that at least the CCL that I've got doesn't recognize neither CP-866 nor CP866
Sure. List of encodings CCL supports is listed in the manual, while SBCL supports CP-866, and this is what I impled in my previous comment :) . Do you mean that regardless of chcp setting I need CP-866 support in the implementation? That sounds odd for me. But ok, now I know what to do if I want to fix that.

**Comment by vityok** [comment] 2018-01-23 15:47
Hi @budden,

I think that the CCL needs proper character encoding support in order to correctly recognize/decode text data. I.e. being able to associate 'ї' with the `CYRILLIC_SMALL_LETTER_YI` for internal representation/processing.

On the other hand, it might be possible to tweak CCL to use `flexi-streams` based input/output processing in the REPL. I didn't investigate it any further, but there seems to be a number of "advanced" alternative REPL implementations, and if they are using flexi-streams it might be possible to configure them for CP-866 (or CP-1251).

Hope this helps,
Victor

**Comment by budden** [comment] 2018-01-23 16:18
Hi! Thanks. That issue is not of high priority, so I think we can disregard it for now. In SWANK everything works, so not having cyrillic in the console is not crucial.

**Comment by xrme** [comment] 2018-01-23 18:25
From reading the comments, it sounds like the issue here is that CCL doesn't support the character encoding CP-866.  Is that right?

In CCL, a `char` (and a `base-char`) is represented internally as a utf-32 code point.  The various character encodings / external formats translate to and from this internal representation.  Adding a new character encoding for CP-866 would be straightforward, and I'd accept a pull request adding that.

I think it would be something like
```
(define-8-bit-fixed-width-encoding :cp866
 "An 8-bit, fixed-width character encoding that includes Cyrillic letters and pseudo-graphic symbols."
 (:csIBM866)
 ...)
```
in https://github.com/Clozure/ccl/blob/master/level-1/l1-unicode.lisp

Note that official character set names are taken from http://www.iana.org/assignments/character-sets/character-sets.xhtml).

On the other hand, CCL certainly supports the UTF-8 encoding, so I would have thought that you could configure the Windows console to use UTF-8.

**Comment by budden** [comment] 2018-01-23 19:05
>  it sounds like the issue here is that CCL doesn't support the character encoding CP-866. Is that right?
If that is the root cause of my issue (incorrect display of Cyrillic characters), I think it is easy to fix and I could do that. But I was actually doing just a quick assesment of CCL with very limited resources, and this was not the main issue I encountered.
> On the other hand, CCL certainly supports the UTF-8 encoding, so I would have thought that you could configure the Windows console to use UTF-8
This didn't work for me, but, again, this is not very important.

**Comment by vityok** [comment] 2018-01-25 12:00
Just to finish it off:

> If that is the root cause of my issue (incorrect display of Cyrillic characters)

The problem is not only that CCL incorrectly displays these characters, but that it incorrectly reads them in the first place. When reading characters from the input stream CCL (or any other Lisp or similar system, even Java) they must be assigned proper internal representation, in this case - UTF-32 code point. But in order to get a single byte (as all characters in CP-866 are) and map it to the correct UTF-32 code point the system must be aware of the coding table. Which is absent in our case.

That's why the issues begin when the characters are being read. But they will also occur when being printed.

However, CP-866/CP-1251/KOI8 all seem to be deprecated nowdays by the more popular UTF-8.

**Comment by xrme** [comment] 2018-03-16 17:51
I just looked at this again for a minute, and according to comments on https://stackoverflow.com/a/388500 (which is, admittedly, rather old), utf-8 handing in the Windows console is not that good.

In your video, you use cp866 when you run sbcl.  Since cp866 is a fixed-width 8-bit encoding, the issue with utf-8 and Window console doesn't appear.  If you were to use utf-8 with sbcl, I think you would see the same problem that you see with ccl.

It looks like the workaround is to use an alternate terminal (for instance, I typically use the Cygwin64 terminal, and it seems to work).  Another option, as I have already mentioned, would be to add cp866 support to CCL.

It would be straightforward (and maybe a little tedious) to add cp866 support to ccl.  If I do that, will anybody test it and use it?  Please let me know.

Otherwise, let's close this issue, because as far as I can tell, the problem is caused by imperfect utf-8 handling by the Windows console, and not by a bug in CCL.

**Comment by xrme** [comment] 2018-03-28 00:29
I added support for the ibm866 (aka cp866, csIBM866) character encoding to the CCL master branch.

```
c:\cygwin64\home\rme\github\ccl>wx86cl64 -K cp866
Clozure Common Lisp Version 1.12-dev/v1.12-dev.3-5-gf3b52e8  (WindowsX8664)
? *terminal-io*
#<ECHOING-TWO-WAY-STREAM input #<BASIC-CHARACTER-INPUT-STREAM IBM866 (CHARACTER-SPECIAL/76) #x2100492BDD>, output #<BASIC-CHARACTER-OUTPUT-STREAM IBM866 (CHARACTER-SPECIAL/80) #x210049224D> #x21004BF78D>
? 'Привет
ПРИВЕТ
?
```
If you'll pull and rebuild with `(rebuild-ccl :clean t)`, I'd like to hear whether this works for you.  Do note that this is currently on the master branch only.

**Comment by vityok** [comment] 2018-03-30 16:30
Hi @xrme thanks for your hard work, but I am running on linux and don't have an easy way to test new functionality. I hope @budden still has interest in making this CP to work on his system.

**Comment by budden** [comment] 2018-03-30 19:44
Hi! I can test it. Is it contained in the last dev build or should I
build from the sources?

2018-03-30 19:30 GMT+03:00, Victor <notifications@github.com>:

**Comment by xrme** [comment] 2018-03-30 21:13
@budden Thank you.  You have to update from the sources.

https://github.com/Clozure/ccl/releases/tag/v1.12-dev.1 has instructions.

Afterwards, just do `git pull`, start the lisp with `wx86cl64.exe` or whatever, and do `(rebuild-ccl :clean t)`.

**Comment by budden** [comment] 2018-04-01 07:40
Hi!
 It works when I run it with -K IBM866 (that was not so trivial to deduce :) )


2018-03-31 0:13 GMT+03:00, R. Matthew Emerson <notifications@github.com>:

**Comment by budden** [comment] 2018-04-01 07:40
P.S. Thanks a lot!

2018-03-31 0:13 GMT+03:00, R. Matthew Emerson <notifications@github.com>:

**Comment by xrme** [comment] 2018-04-02 18:26
I'm glad to hear it works for you.

**Closed by xrme** 2018-04-02 18:26 UTC
